#!/usr/bin/env python3
"""Generate STATE_DIGEST.md: a compact, READ-ONLY view of the registries.

The digest is derived and never authoritative; the registries win on any conflict.
Usage: brain_digest.py [--root PATH] [--stdout]
"""
import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import brain_check  # noqa: E402
import brain_lib as lib  # noqa: E402


def build(root):
    root = Path(root)
    schemas, workflow = lib.load_schemas(root)
    rep = brain_check.run_checks(root)
    data = {n: lib.read_csv(root / s["path"])[1] for n, s in schemas.items()}
    snap = hashlib.sha256()
    for n in sorted(schemas):
        snap.update((root / schemas[n]["path"]).read_bytes())
    out = ["# STATE_DIGEST", "",
           "> Generated by `tools/brain_digest.py`. Derived and non-authoritative; registries win on any conflict.", "",
           f"- registry_snapshot_hash: `{snap.hexdigest()[:16]}`",
           f"- brain_check: {len(rep.errors)} error(s), {len(rep.warnings)} warning(s)", ""]
    out += ["## Chapters", "", "| Chapter | Phase | Locked rev |", "|---|---|---|"]
    out += [f"| {c['chapter_id']} {c['title']} | {c['phase']} | {c['locked_revision'] or '-'} |" for c in data["chapters"]]
    ok, reasons = lib.gate_status(data["chapters"], workflow)
    out += ["", "## Translation gate", "", "OPEN" if ok else "CLOSED: " + "; ".join(reasons)]
    block = lib.ethics_block_reasons(lib.parse_project_state(root))
    out += ["", "## Ethics guard", "", "participant-data work allowed" if not block else "BLOCKED: " + "; ".join(block)]
    open_items = [w for w in data["work_items"] if w["state"] in ("PROPOSED", "ACTIVE", "BLOCKED")]
    out += ["", "## Open work items", ""]
    out += [f"- {w['work_item_id']} [{w['state']}] {w['title']}" for w in open_items] or ["- none"]
    if rep.errors:
        out += ["", "## Check errors", ""] + [f"- {e}" for e in rep.errors]
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=str(lib.DEFAULT_ROOT))
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args(argv)
    text = build(args.root)
    if args.stdout:
        print(text, end="")
    else:
        (Path(args.root) / "00_START_HERE/STATE_DIGEST.md").write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
